// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/iremake/common/network/messages/messages.proto

package org.iremake.common.network.messages;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .messages.Msg.Type type = 1;
    boolean hasType();
    org.iremake.common.network.messages.Messages.Msg.Type getType();
    
    // optional .messages.Text text = 2;
    boolean hasText();
    org.iremake.common.network.messages.Messages.Text getText();
    org.iremake.common.network.messages.Messages.TextOrBuilder getTextOrBuilder();
  }
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(Builder builder) {
      super(builder);
    }
    private Msg(boolean noInit) {}
    
    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iremake.common.network.messages.Messages.internal_static_messages_Msg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iremake.common.network.messages.Messages.internal_static_messages_Msg_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      TEXT(0, 1),
      ;
      
      public static final int TEXT_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return TEXT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.iremake.common.network.messages.Messages.Msg.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        TEXT, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:messages.Msg.Type)
    }
    
    private int bitField0_;
    // required .messages.Msg.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.iremake.common.network.messages.Messages.Msg.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.iremake.common.network.messages.Messages.Msg.Type getType() {
      return type_;
    }
    
    // optional .messages.Text text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private org.iremake.common.network.messages.Messages.Text text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.iremake.common.network.messages.Messages.Text getText() {
      return text_;
    }
    public org.iremake.common.network.messages.Messages.TextOrBuilder getTextOrBuilder() {
      return text_;
    }
    
    private void initFields() {
      type_ = org.iremake.common.network.messages.Messages.Msg.Type.TEXT;
      text_ = org.iremake.common.network.messages.Messages.Text.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasText()) {
        if (!getText().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, text_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.iremake.common.network.messages.Messages.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.iremake.common.network.messages.Messages.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.iremake.common.network.messages.Messages.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iremake.common.network.messages.Messages.internal_static_messages_Msg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iremake.common.network.messages.Messages.internal_static_messages_Msg_fieldAccessorTable;
      }
      
      // Construct using org.iremake.common.network.messages.Messages.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTextFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = org.iremake.common.network.messages.Messages.Msg.Type.TEXT;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (textBuilder_ == null) {
          text_ = org.iremake.common.network.messages.Messages.Text.getDefaultInstance();
        } else {
          textBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iremake.common.network.messages.Messages.Msg.getDescriptor();
      }
      
      public org.iremake.common.network.messages.Messages.Msg getDefaultInstanceForType() {
        return org.iremake.common.network.messages.Messages.Msg.getDefaultInstance();
      }
      
      public org.iremake.common.network.messages.Messages.Msg build() {
        org.iremake.common.network.messages.Messages.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.iremake.common.network.messages.Messages.Msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.iremake.common.network.messages.Messages.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.iremake.common.network.messages.Messages.Msg buildPartial() {
        org.iremake.common.network.messages.Messages.Msg result = new org.iremake.common.network.messages.Messages.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (textBuilder_ == null) {
          result.text_ = text_;
        } else {
          result.text_ = textBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iremake.common.network.messages.Messages.Msg) {
          return mergeFrom((org.iremake.common.network.messages.Messages.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.iremake.common.network.messages.Messages.Msg other) {
        if (other == org.iremake.common.network.messages.Messages.Msg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasText()) {
          mergeText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasText()) {
          if (!getText().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.iremake.common.network.messages.Messages.Msg.Type value = org.iremake.common.network.messages.Messages.Msg.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              org.iremake.common.network.messages.Messages.Text.Builder subBuilder = org.iremake.common.network.messages.Messages.Text.newBuilder();
              if (hasText()) {
                subBuilder.mergeFrom(getText());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setText(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .messages.Msg.Type type = 1;
      private org.iremake.common.network.messages.Messages.Msg.Type type_ = org.iremake.common.network.messages.Messages.Msg.Type.TEXT;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.iremake.common.network.messages.Messages.Msg.Type getType() {
        return type_;
      }
      public Builder setType(org.iremake.common.network.messages.Messages.Msg.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.iremake.common.network.messages.Messages.Msg.Type.TEXT;
        onChanged();
        return this;
      }
      
      // optional .messages.Text text = 2;
      private org.iremake.common.network.messages.Messages.Text text_ = org.iremake.common.network.messages.Messages.Text.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.iremake.common.network.messages.Messages.Text, org.iremake.common.network.messages.Messages.Text.Builder, org.iremake.common.network.messages.Messages.TextOrBuilder> textBuilder_;
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.iremake.common.network.messages.Messages.Text getText() {
        if (textBuilder_ == null) {
          return text_;
        } else {
          return textBuilder_.getMessage();
        }
      }
      public Builder setText(org.iremake.common.network.messages.Messages.Text value) {
        if (textBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          text_ = value;
          onChanged();
        } else {
          textBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setText(
          org.iremake.common.network.messages.Messages.Text.Builder builderForValue) {
        if (textBuilder_ == null) {
          text_ = builderForValue.build();
          onChanged();
        } else {
          textBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeText(org.iremake.common.network.messages.Messages.Text value) {
        if (textBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              text_ != org.iremake.common.network.messages.Messages.Text.getDefaultInstance()) {
            text_ =
              org.iremake.common.network.messages.Messages.Text.newBuilder(text_).mergeFrom(value).buildPartial();
          } else {
            text_ = value;
          }
          onChanged();
        } else {
          textBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearText() {
        if (textBuilder_ == null) {
          text_ = org.iremake.common.network.messages.Messages.Text.getDefaultInstance();
          onChanged();
        } else {
          textBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.iremake.common.network.messages.Messages.Text.Builder getTextBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTextFieldBuilder().getBuilder();
      }
      public org.iremake.common.network.messages.Messages.TextOrBuilder getTextOrBuilder() {
        if (textBuilder_ != null) {
          return textBuilder_.getMessageOrBuilder();
        } else {
          return text_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.iremake.common.network.messages.Messages.Text, org.iremake.common.network.messages.Messages.Text.Builder, org.iremake.common.network.messages.Messages.TextOrBuilder> 
          getTextFieldBuilder() {
        if (textBuilder_ == null) {
          textBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.iremake.common.network.messages.Messages.Text, org.iremake.common.network.messages.Messages.Text.Builder, org.iremake.common.network.messages.Messages.TextOrBuilder>(
                  text_,
                  getParentForChildren(),
                  isClean());
          text_ = null;
        }
        return textBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Msg)
    }
    
    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Msg)
  }
  
  public interface TextOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string text = 1;
    boolean hasText();
    String getText();
  }
  public static final class Text extends
      com.google.protobuf.GeneratedMessage
      implements TextOrBuilder {
    // Use Text.newBuilder() to construct.
    private Text(Builder builder) {
      super(builder);
    }
    private Text(boolean noInit) {}
    
    private static final Text defaultInstance;
    public static Text getDefaultInstance() {
      return defaultInstance;
    }
    
    public Text getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iremake.common.network.messages.Messages.internal_static_messages_Text_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iremake.common.network.messages.Messages.internal_static_messages_Text_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      VERSION(0, 0),
      REGISTER(1, 1),
      ;
      
      public static final int VERSION_VALUE = 0;
      public static final int REGISTER_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return VERSION;
          case 1: return REGISTER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.iremake.common.network.messages.Messages.Text.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        VERSION, REGISTER, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:messages.Text.Type)
    }
    
    private int bitField0_;
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.iremake.common.network.messages.Messages.Text parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Text parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Text parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Text parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Text parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Text parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Text parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.iremake.common.network.messages.Messages.Text parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.iremake.common.network.messages.Messages.Text parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.iremake.common.network.messages.Messages.Text parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.iremake.common.network.messages.Messages.Text prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.iremake.common.network.messages.Messages.TextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iremake.common.network.messages.Messages.internal_static_messages_Text_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iremake.common.network.messages.Messages.internal_static_messages_Text_fieldAccessorTable;
      }
      
      // Construct using org.iremake.common.network.messages.Messages.Text.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iremake.common.network.messages.Messages.Text.getDescriptor();
      }
      
      public org.iremake.common.network.messages.Messages.Text getDefaultInstanceForType() {
        return org.iremake.common.network.messages.Messages.Text.getDefaultInstance();
      }
      
      public org.iremake.common.network.messages.Messages.Text build() {
        org.iremake.common.network.messages.Messages.Text result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.iremake.common.network.messages.Messages.Text buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.iremake.common.network.messages.Messages.Text result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.iremake.common.network.messages.Messages.Text buildPartial() {
        org.iremake.common.network.messages.Messages.Text result = new org.iremake.common.network.messages.Messages.Text(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iremake.common.network.messages.Messages.Text) {
          return mergeFrom((org.iremake.common.network.messages.Messages.Text)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.iremake.common.network.messages.Messages.Text other) {
        if (other == org.iremake.common.network.messages.Messages.Text.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string text = 1;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Text)
    }
    
    static {
      defaultInstance = new Text(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Text)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Text_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Text_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2org/iremake/common/network/messages/me" +
      "ssages.proto\022\010messages\"W\n\003Msg\022 \n\004type\030\001 " +
      "\002(\0162\022.messages.Msg.Type\022\034\n\004text\030\002 \001(\0132\016." +
      "messages.Text\"\020\n\004Type\022\010\n\004TEXT\020\001\"7\n\004Text\022" +
      "\014\n\004text\030\001 \002(\t\"!\n\004Type\022\013\n\007VERSION\020\000\022\014\n\010RE" +
      "GISTER\020\001B%\n#org.iremake.common.network.m" +
      "essages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Msg_descriptor,
              new java.lang.String[] { "Type", "Text", },
              org.iremake.common.network.messages.Messages.Msg.class,
              org.iremake.common.network.messages.Messages.Msg.Builder.class);
          internal_static_messages_Text_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messages_Text_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Text_descriptor,
              new java.lang.String[] { "Text", },
              org.iremake.common.network.messages.Messages.Text.class,
              org.iremake.common.network.messages.Messages.Text.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
