/*
 * Copyright (C) 2012 Trilarion
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.iremake.network;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ScrollPaneConstants;
import javax.swing.WindowConstants;
import org.iremake.client.network.Client;
import org.iremake.server.network.StartServer;
import org.tools.ui.helper.LookAndFeel;

/**
 *
 */
public class ConnectionTest extends JFrame {
    
    private boolean activeServer = false;

    /**
     * Creates new form ConnectionTest
     */
    public ConnectionTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverStartButton = new JButton();
        serverTextScrollPane = new JScrollPane();
        serverTextArea = new JTextArea();
        clientStartButton = new JButton();
        clientTextScrollPane = new JScrollPane();
        clientTextArea = new JTextArea();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new Dimension(400, 400));

        serverStartButton.setText("Start Server");
        serverStartButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                serverStartButtonActionPerformed(evt);
            }
        });

        serverTextScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        serverTextArea.setColumns(20);
        serverTextArea.setRows(5);
        serverTextScrollPane.setViewportView(serverTextArea);

        clientStartButton.setText("Start a Client");
        clientStartButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clientStartButtonActionPerformed(evt);
            }
        });

        clientTextScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        clientTextArea.setColumns(20);
        clientTextArea.setRows(5);
        clientTextScrollPane.setViewportView(clientTextArea);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(clientTextScrollPane, GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(serverTextScrollPane, Alignment.LEADING)
                    .addGroup(Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(serverStartButton)
                            .addComponent(clientStartButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serverStartButton)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(serverTextScrollPane, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(clientStartButton)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(clientTextScrollPane, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverStartButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_serverStartButtonActionPerformed
        if (activeServer == false) {
            activeServer = true;
            StartServer.run();
        }
    }//GEN-LAST:event_serverStartButtonActionPerformed

    private void clientStartButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clientStartButtonActionPerformed
        // start client
        new Client("localhost", 19876, 256).run();        
    }//GEN-LAST:event_clientStartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LookAndFeel.setSystemLookAndFeel();

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConnectionTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton clientStartButton;
    private JTextArea clientTextArea;
    private JScrollPane clientTextScrollPane;
    private JButton serverStartButton;
    private JTextArea serverTextArea;
    private JScrollPane serverTextScrollPane;
    // End of variables declaration//GEN-END:variables
}
