/*
 * Copyright (C) 2012 Trilarion
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.iremake.network;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ScrollPaneConstants;
import javax.swing.WindowConstants;
import org.iremake.client.network.ClientManager;
import org.iremake.common.network.NetworkLogger;
import org.iremake.common.network.messages.TextMessage;
import org.tools.ui.utils.LookAndFeel;
import org.iremake.server.network.ServerManager;

/**
 * Tests the Client and Server via a graphical user interface, and some logging
 * output to some text areas.
 */
public class ClientServerConsole extends JFrame {
    private static final long serialVersionUID = 1L;

    private ServerManager server;
    private ClientManager client;

    /**
     * Creates new form ClientServerSniffer
     */
    public ClientServerConsole() {
        initComponents();

        // client and server manager
        NetworkLogger serverLogger = new NetworkLogger() {
            @Override
            public void log(String message) {
                ClientServerConsole.this.serverMessage(message);
            }
        };
        server = new ServerManager(serverLogger);
        NetworkLogger clientLogger = new NetworkLogger() {
            @Override
            public void log(String message) {
                ClientServerConsole.this.clientMessage(message);
            }
        };
        client = new ClientManager(clientLogger);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverStart = new JButton();
        serverStop = new JButton();
        serverScrollPane = new JScrollPane();
        serverTextArea = new JTextArea();
        clientStart = new JButton();
        clientName = new JButton();
        clientScrollPane = new JScrollPane();
        clientTextArea = new JTextArea();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Server Console");
        setLocationByPlatform(true);
        setMinimumSize(new Dimension(600, 400));
        setResizable(false);

        serverStart.setText("Start");
        serverStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                serverStartActionPerformed(evt);
            }
        });

        serverStop.setText("Stop");
        serverStop.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                serverStopActionPerformed(evt);
            }
        });

        serverScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        serverScrollPane.setMinimumSize(new Dimension(400, 200));

        serverTextArea.setColumns(20);
        serverTextArea.setFont(new Font("Monospaced", 0, 12)); // NOI18N
        serverTextArea.setRows(5);
        serverScrollPane.setViewportView(serverTextArea);

        clientStart.setText("Start");
        clientStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clientStartActionPerformed(evt);
            }
        });

        clientName.setText("Name");
        clientName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clientNameActionPerformed(evt);
            }
        });

        clientScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        clientScrollPane.setMinimumSize(new Dimension(400, 200));

        clientTextArea.setColumns(20);
        clientTextArea.setFont(new Font("Monospaced", 0, 12)); // NOI18N
        clientTextArea.setRows(5);
        clientScrollPane.setViewportView(clientTextArea);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(clientScrollPane, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addComponent(serverScrollPane, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serverStart)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(serverStop))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientStart)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(clientName)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(serverStart)
                    .addComponent(serverStop))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(serverScrollPane, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(clientStart)
                    .addComponent(clientName))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(clientScrollPane, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverStartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_serverStartActionPerformed
        server.start();
    }//GEN-LAST:event_serverStartActionPerformed

    private void serverStopActionPerformed(ActionEvent evt) {//GEN-FIRST:event_serverStopActionPerformed
        server.stop();
    }//GEN-LAST:event_serverStopActionPerformed

    private void clientStartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clientStartActionPerformed
        client.start();
    }//GEN-LAST:event_clientStartActionPerformed

    private void clientNameActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clientNameActionPerformed
        client.send(new TextMessage("John Doe", TextMessage.Type.ClientName));
    }//GEN-LAST:event_clientNameActionPerformed
    private int counter = 0;

    private void serverMessage(String message) {
        counter++;
        String text = serverTextArea.getText();
        serverTextArea.setText(counter + ": " + message + "\r\n" + text);
    }

    private void clientMessage(String message) {
        counter++;
        String text = clientTextArea.getText();
        clientTextArea.setText(counter + ": " + message + "\r\n" + text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        LookAndFeel.setSystemLookAndFeel();

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClientServerConsole().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton clientName;
    private JScrollPane clientScrollPane;
    private JButton clientStart;
    private JTextArea clientTextArea;
    private JScrollPane serverScrollPane;
    private JButton serverStart;
    private JButton serverStop;
    private JTextArea serverTextArea;
    // End of variables declaration//GEN-END:variables
}
